name: ghpages
on:
 push:
   branches:
     - main
# permissions:
#   actions: write
#   contents: write
#   deployments: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/cache@v2  
        with:
          python-version: 3.11.5

        with:
          key: ${{github.ref}}  
          path: .cache
      - name: run requirements file
        run:  pip install -r requirements.txt
#	run: pip install -e .
      - name: Deploy docs
        run: mkdocs gh-deploy --force
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
